// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1AJKx7nGh-XadqXnCxmzPBzIh1UNgvtg',
    appId: '1:592398121414:web:fc5b092619f08b6894dac7',
    messagingSenderId: '592398121414',
    projectId: 'mahara-todo-list-backend',
    authDomain: 'mahara-todo-list-backend.firebaseapp.com',
    storageBucket: 'mahara-todo-list-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkpEa4pjAhDKnJyh1Vf7rHmVp2gNKGsE',
    appId: '1:592398121414:android:7da50e984e7ba51a94dac7',
    messagingSenderId: '592398121414',
    projectId: 'mahara-todo-list-backend',
    storageBucket: 'mahara-todo-list-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA420EjlQmZw52OFXERV63S1hvP9QepHFQ',
    appId: '1:592398121414:ios:4535bbdc1a24bd7f94dac7',
    messagingSenderId: '592398121414',
    projectId: 'mahara-todo-list-backend',
    storageBucket: 'mahara-todo-list-backend.appspot.com',
    iosBundleId: 'com.example.todoListBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA420EjlQmZw52OFXERV63S1hvP9QepHFQ',
    appId: '1:592398121414:ios:2b96843c8511c45194dac7',
    messagingSenderId: '592398121414',
    projectId: 'mahara-todo-list-backend',
    storageBucket: 'mahara-todo-list-backend.appspot.com',
    iosBundleId: 'com.example.todoListBackend.RunnerTests',
  );
}
